// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/pagination.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pagination struct {
	Total                uint64   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PerPage              uint32   `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	CurrentPage          uint32   `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	LastPage             uint32   `protobuf:"varint,4,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_32786bed7c1d7413, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetPerPage() uint32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Pagination) GetCurrentPage() uint32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Pagination) GetLastPage() uint32 {
	if m != nil {
		return m.LastPage
	}
	return 0
}

func init() {
	proto.RegisterType((*Pagination)(nil), "protos.Pagination")
}

func init() {
	proto.RegisterFile("protos/pagination.proto", fileDescriptor_32786bed7c1d7413)
}

var fileDescriptor_32786bed7c1d7413 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x48, 0x4c, 0xcf, 0xcc, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x8b,
	0x08, 0xb1, 0x41, 0x24, 0x94, 0x6a, 0xb9, 0xb8, 0x02, 0xe0, 0x72, 0x42, 0x22, 0x5c, 0xac, 0x25,
	0xf9, 0x25, 0x89, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x10, 0x8e, 0x90, 0x24, 0x17,
	0x47, 0x41, 0x6a, 0x51, 0x7c, 0x41, 0x62, 0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6f, 0x10,
	0x7b, 0x41, 0x6a, 0x51, 0x40, 0x62, 0x7a, 0xaa, 0x90, 0x22, 0x17, 0x4f, 0x72, 0x69, 0x51, 0x51,
	0x6a, 0x5e, 0x09, 0x44, 0x9a, 0x19, 0x2c, 0xcd, 0x0d, 0x15, 0x03, 0x2b, 0x91, 0xe6, 0xe2, 0xcc,
	0x49, 0x2c, 0x86, 0xca, 0xb3, 0x80, 0xe5, 0x39, 0x40, 0x02, 0x20, 0x49, 0x27, 0xd6, 0x28, 0x66,
	0xfd, 0x82, 0xa4, 0x24, 0x88, 0x6b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0x55, 0x08,
	0x70, 0xaf, 0x00, 0x00, 0x00,
}
